# Generated by Django 4.1 on 2022-08-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Admin', max_length=250),
            preserve_default=False,
        ),
    ]
